# Generated by Django 6.0.3 on 2026-03-15 10:37

import apps.verification.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_full_name', models.CharField(max_length=255)),
                ('id_type', models.CharField(choices=[('kebele', 'Kebele ID'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('national_id', 'National ID')], max_length=20)),
                ('id_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review')], default='pending', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('verification_data', models.JSONField(default=dict)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('id_front', 'ID Front'), ('id_back', 'ID Back'), ('selfie', 'Selfie'), ('signature', 'Signature')], max_length=20)),
                ('file', models.ImageField(upload_to=apps.verification.models.kyc_document_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.verification.models.kyc_document_path)),
                ('ocr_text', models.TextField(blank=True)),
                ('face_detected', models.BooleanField(default=False)),
                ('quality_score', models.FloatField(default=0.0)),
                ('processing_errors', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='verification.kycsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('auto_approved', 'Auto Approved'), ('auto_rejected', 'Auto Rejected'), ('manual_approved', 'Manual Approved'), ('manual_rejected', 'Manual Rejected'), ('flagged', 'Flagged'), ('updated', 'Updated')], max_length=20)),
                ('performed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='verification.kycsubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='kycsubmission',
            index=models.Index(fields=['user_id'], name='verificatio_user_id_86db7a_idx'),
        ),
        migrations.AddIndex(
            model_name='kycsubmission',
            index=models.Index(fields=['status'], name='verificatio_status_1825a8_idx'),
        ),
        migrations.AddIndex(
            model_name='kycsubmission',
            index=models.Index(fields=['created_at'], name='verificatio_created_a7cb13_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kycdocument',
            unique_together={('submission', 'document_type')},
        ),
    ]
